title()
capitalize()
center(width,fillchar)
count(str,beg=0,end=len(string))
decode(encoding='UTF-8',errors='strict')
endswith(suffix,beg=0,end=len(string))
expandtabs(tabsize=8)
find(str,beg=0,end=len(string))
index(str,beg=0,end=len(string))
isalnum()
encode(encoding="UTF-8",errors="strick")
isalpha()
isdigit()
islower()
isnumeric()
isspace()
isupper()
join(seq)
len(string)
ljust()
istitle()
lower()
istrip()
maketrans()
isdecimal()
max(str)
replace(old,new,[max])
rfind(str,beg=0,end=len(string))
rindex(str,beg=0,end=len(string))
rjust(width,[fillchar])
rstrip()
split(str="",num=string.count(str))
min(str)
splitlines(num=string.count('\n'))
startswith(str,beg=0,end=len(string))
strip([chars])




